handle multiple buttons in Cookie banner as per current GDS Cookie ba…
dvsa/cookie-manager pull request #21
Opened 2021-10-20 10:01 UTC by bennetts101

Changes to support new GDS design for cookie banner with multiple action buttons.

2021-10-20 10:42 UTC, jerotire approved these changes

2021-10-20 15:21 UTC, JoshuaLicense requested changes

2021-10-20 15:21 UTC, JoshuaLicense commented on cookie-manager.js
> +            for (let button of cookieButtons) {
We may need to refactor `for... of`. It is not compatible with IE11 ([GDS Browser support list](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices)).

Just a `for` loop may be more compatible.

2021-10-21 07:16 UTC, sdh100shaun commented
The index.html example has not been updated to reflect the new pattern.  Please ensure built as per GDS design system. Have we tested the change manually?

2021-10-21 09:30 UTC, JoshuaLicense requested changes
Could the README be updated to reflect the new changes please? 

https://github.com/dvsa/cookie-manager#feature-cookie-banner is inaccurate after this change.

2021-10-25 07:29 UTC, merged